name: customer_app
description: A Flutter customer service booking application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.20.2
  image_picker: ^1.0.0
  path_provider: ^2.0.15
  pdf: ^3.10.4
  share_plus: ^7.0.2
  geolocator: ^11.0.0
  geocoding: ^2.1.1
  http: ^1.1.0
  firebase_core: ^2.31.0
  firebase_auth: ^4.17.3
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  cloud_firestore: ^4.17.5
  shared_preferences: ^2.5.4
  flutter_local_notifications: ^19.5.0
  firebase_messaging: ^14.9.4
  url_launcher: ^6.3.2
  connectivity_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo_padded_v4.png"

flutter:
  uses-material-design: true
  generate: true  # Enable localization code generation

  assets:
    - assets/images/
    - assets/images/Aidea_logo.png
    - assets/images/ac_service.png
    - assets/images/home_appliances.png
    - assets/images/plumbing.png
    - assets/images/electric.png
    - assets/fonts/