name: customer_app
description: A Flutter customer service booking application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.20.2
  image_picker: ^1.0.0
  path_provider: ^2.0.15
  pdf: ^3.10.4
  share_plus: ^7.0.2
  geolocator: ^11.0.0
  geocoding: ^2.1.1
  http: ^1.1.0
  firebase_core: ^2.31.0
  firebase_auth: ^4.17.3
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  cloud_firestore: ^4.17.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true  # Enable localization code generation

  assets:
    - assets/images/
    - assets/images/Aidea_logo.png
    - assets/images/ac_service.png
    - assets/images/home_appliances.png
    - assets/images/plumbing.png
    - assets/images/electric.png